added checks of input format, changed out file format

diff --git a/cpack b/cpack
--- a/cpack
+++ b/cpack
@@ -1,41 +1,63 @@
 #!/bin/bash
 
-#cleanup
-rm cpack.$1 2> /dev/null
-if [ $? -eq 0 ]
-then
-    echo "Removed existing file cpack.$1"
-fi
-rm out.$1 2> /dev/null
-if [ $? -eq 0 ]
-then
-    echo "Removed existing file out.$1"
-fi
-
-#finding flags
+#flag setup 
 full_path=$(realpath $0)
 dir_path=$(dirname $full_path)
 flags=$(sed -z 's/\n/ /g' $dir_path/flags)
 
-#compiling
+#file validity checks
+if [ "$#" -ne 1 ]
+then
+  echo "Usage: cpack <source file>"
+  exit 1
+fi  
+
+if [[ -f "$1" ]]; then  
+    true
+else
+    echo "Nonexistant file, exiting"
+    exit 1
+fi  
+
+#names setup
+packname=$1.cpack.cpp
+outname=$(echo $1 | cut -f1 -d".").out
+
+#cleanup
+rm $packname 2> /dev/null
+if [ $? -eq 0 ]
+then
+    echo "Removed existing file $packname"
+fi
+rm $outname 2> /dev/null
+if [ $? -eq 0 ]
+then
+    echo "Removed existing file $outname"
+fi
+
+#compiling source
 echo "Using flags: $flags"
-g++ $flags $1 -o out.$1
+echo 
+
+g++ $flags $1 -o $outname
+echo
 if [ $? -ne 0 ]
 then
-    echo "[FAIL] Compilation of out.$1 failed!"
-    exit;
+    echo "[FAIL] Compilation of source failed!"
+    exit 1
 else
-    echo "Compilation of out.$1 done!"
+    echo "Compilation of source done! ($outname)"
 fi
 
 #source packaging
-g++ -E -D"COMP_PROG_DEPLOY" $1  | sed 's/#pragma DELETETHISPREFIX//g' | sed '/^#.*/d' > cpack.$1
+g++ -E -D"COMP_PROG_DEPLOY" $1  |\
+    sed 's/#pragma DELETETHISPREFIX//g' |\
+    sed '/^#.*/d' > $packname 
 if [ $? -ne 0 ]
 then
-    echo "[FAIL] Packaging of cpack.$1 failed!"
-    rm out.$1
-    exit;
+    echo "[FAIL] Packaging of source failed!"
+    rm $outname
+    exit 1
 else
-    echo "Packaging of cpack.$1 done!"
+    echo "Packaging of source done!   ($packname)"
 fi
-
