fixed messages, compiling is now on original file

diff --git a/cpack b/cpack
--- a/cpack
+++ b/cpack
@@ -17,25 +17,25 @@ full_path=$(realpath $0)
 dir_path=$(dirname $full_path)
 flags=$(sed -z 's/\n/ /g' $dir_path/flags)
 
+#compiling
+echo "Using flags: $flags"
+g++ $flags $1 -o out.$1
+if [ $? -ne 0 ]
+then
+    echo "[FAIL] Compilation of out.$1 failed!"
+    exit;
+else
+    echo "Compilation of out.$1 done!"
+fi
 
 #source packaging
 g++ -E -D"COMP_PROG_DEPLOY" $1  | sed 's/#pragma DELETETHISPREFIX//g' | sed '/^#.*/d' > cpack.$1
 if [ $? -ne 0 ]
 then
     echo "[FAIL] Packaging of cpack.$1 failed!"
+    rm out.$1
     exit;
 else
     echo "Packaging of cpack.$1 done!"
 fi
 
-#compiling
-echo "Using flags: $flags"
-g++ $flags cpack.$1 -o out.$1
-if [ $? -ne 0 ]
-then
-    echo "[FAIL] Compilation of cpack.$1 failed!"
-    rm cpack.$1
-    exit;
-else
-    echo "Compilation of cpack.$1 done!"
-fi
